### ISSUE TITLE
Port SK web template to angular-2

### ISSUE THREAD

**Issue by sinedied** [angular-starter-kit/ngx-starter-kit#1]
Use angular-cli as a start for the tooling,
Then port the web template using:

- Angular 2 (obviously)
- Bootstrap 4
- Font Awesome
- Same responsive design (or close enough)

**Comment by gaetanmaisse** [comment]
Pour la gestion des libs "à embarquer dans l'appli" (Bootstrap, Lodash...), il y a deux possibilités : 
- Bower avec un fonctionnement calqué sur celui du ST1
- NPM avec l'ajout des libs dans le fichier angular-cli.json, comme présenté dans le [readme](https://github.com/angular/angular-cli#global-library-installation) de Angular CLI

D'un coté le fonctionnement avec Bower & NPM permet d'avoir une distinction claire entre l'utilité des 2 outils. D'un autre coté, ça fait 2 outils à gérer au lieu d'un et Nexus (Sonatype Nexus Repo Manager) ne gère les repo bower que dans sa dernière version.

Je suis preneur d'autres avis :)

**Comment by creal73** [comment]
Je suis plutôt partant pour n'utiliser que npm qui semble être la norme aujourd'hui. D'autant plus que la distinction entre dépendances applicatives et dépendances de build se fait à travers les propriétés "dependencies" et "devDependencies" dans le package.json.

**Comment by sinedied** [comment]
NPM only, as designed by angular-cli, but you do not need to add libs in `angular-cli.json`, only the ones that should be exposed "globally" in the app (like jquery, but today we need none).

All libs should be imported like any other ES6 module directly in your files, for example:
`import { moment } from 'moment';`
