### ISSUE TITLE
erreur sur la commande npm install

### ISSUE THREAD

**Issue by lebesnec** [angular-starter-kit/ngx-starter-kit#18]
j'a l'erreur suivante quand je lance la commande `npm install` :

`
ERROR in ./src/app/core/i18n.service.ts
Module build failed: Error: C:/Users/Thales/Documents/GitHub/ngx-starter-kit/src
/app/core/i18n.service.ts (3,10): Module '"C:/Users/Thales/Documents/GitHub/ngx-
starter-kit/node_modules/@types/lodash/index"' has no exported member 'includes'
.)
    at _checkDiagnostics (C:\Users\Thales\Documents\GitHub\ngx-starter-kit\node_
modules\@ngtools\webpack\src\loader.js:145:15)
    at C:\Users\Thales\Documents\GitHub\ngx-starter-kit\node_modules\@ngtools\we
bpack\src\loader.js:172:17
 @ ./src/app/app.component.ts 22:0-50
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
`

j'ai l'impression que la dernière version de lodash fout le bordel. Quand je force la version en virant le "^" sur @types/lodash dans le package.json (ligne 43) ça marche.

**Comment by sinedied** [comment]
I will check this, thanks for the report

**Comment by sinedied** [comment]
I fixed the version until the issue on the typings are resolved, seems to be due to this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14288

**Comment by Sheeo** [comment]
@sinedied you have a locked down dependency on TypeScript 2.0.10 in your [package.json file](https://github.com/angular-starter-kit/ngx-starter-kit/blob/master/package.json#L64).

Upgrading to TypeScript 2.1 will resolve this problem as well.

**Comment by sinedied** [comment]
@Sheeo TypeScript 2.1 does not play well with Angular at the moment, I will have to wait until [this PR](https://github.com/angular/angular/pull/13294) is merged for the upgrade.
